sudo: required
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x mvnw
script:
- "./mvnw clean install -B"
- "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar"
env:
  global:
  # DOCKER_USER
  - secure: BptDeLZo2I0uoCmPDFt22g1kqycj8RjiuocrLYrbe4wm6k+bGoEm/Jr6Ed/oq+jb5Zy3ylS11sqYYSghx3PGxXr3Y1f2qkQcun3spoZm2A8oXfBVrp2tbaEsBnsGCEq8AKvWHQoQ5r5JgJ3bSzBCUeRlUTmWJsiXaBOHuWpMm192B9QblwBoul4lgjmzAdyqelcMzYcLzsTaPQA+YYqQk43+uercDz9lJbv36f1fjWmVdOUGhpe7xoRvB6wGQX+11MKc0EnNj/hJ8VLyfsGE14aj9HRqz+Fey6oi5WhvCv35NtouisQ1Gzm/DwtqsK7Rx2lJaj30O36LTUoAsuCuGu/wfyIdA8JduUh+3SNzJsgKGu8bhNpn2CESQ3ARYkGifLvVrxO9GQfvsuKpq/hU2/sH0v3XppFeEHGLOCPCkXI8MZSbNmrfkbgSRuD7yp104bmwhQuUAUDX3ZRcEO3pX1OfogQJqsB0/4RsUh0GScOsAwqREPl7RB+Z+tA18hQA1bd4zmXS30oyP0pDavWV+do4A919ZYUvm6p41B5//4rY8KSubPwhlsJwgNNaY7pQZiwFbvw+Tl6dDRUUyK1I5f6W1QzZT4eFdmWwSQWLg0DfsmP3C1ULIleigHB54bKogonZqmj9PTk46v1iFuNsA7ikiFEHJ6deNM9ot/M3JMc=
  # DOCKER_PASS
  - secure: atSQrBcDDJa7SMIeZBjUkF09s9OixWgtKFvX4qx4yB2gN5JO+GBbLUxtiGnrqQYFWA69qQE7saXITwlZB7XkMGMG8WIG8bgEBllB6+DtIcR6NKGMeki03MPMLcoz9ViAUbrbpU2eyBRgqEkS5qWia4Wg3BNwDy0Jc4X5CLrOjLGH4/ZyMQZqa9NWe7/6QzlYhcj+/WnNxj/5qrJi9BzdcAxyyuV+1V8n+5z9wSZunS18b4JDvGRBEBbrzY8ogAfUWy7Uj///8P9TcOE24Plu//Fhd3L5RAlNy5IIbzX4sRHUg5gzhcdostMdwv4Sewu8/0YYoI0mtqI1F1ejEo33wJrssegK1p0ldkR/vEIDqZLn/yb8aWS4XPWVhOypJgQEDNDE+JFwOt+k6wd41laJ64ZhXtTxaA1ipbCp98Pg/EibGLeAfkPYOKbGrP5kTKjVN01DS0KHWqkcUUx5dtExRI4qn1YLGBVo3LMLZkGENYUx8zAg4P8Jq1R/SU7T0okmT7K2KtD8Ps148pP7RrjteG6b3QYOX720wOEFncd1JhDfhLrVRmV4GxjYMv9mlOAqTcwT2UZwXXMYtBRuczVAJZdgBOW+ScUx1VZQPcpWflZeEoDabnJ8QNmvS7vRtEPkGlnabOyCDuJlwGCo9tNvGZfpjSziu6F4Fi5uxJJs7LY=
  - COMMIT=${TRAVIS_COMMIT::7}
addons:
  sonarcloud:
    organization: footballassitantteam
    token:
      secure: HYEiRiQ9e6vKEjbExZBvl4ZYrR41nfOfAZ/oMMWY077ragWva/7ePwqG3aQHwuBMmjZXJ1eqoG5FbPIm8+ypK7vMufsPtp/blY2myZMuqYGoCXT58i87k0mWaNetNOTrAZ6jGJxy8Bn/8Q2OFY8r/IOhnji7Grj68sQpPS1mLLNtRbuX0/diZLQ8n/7xLpSjmPIYYcwMRSkKbEL6FfEH31846pWjyHMpQvQd+x4hEbyglxJ900jkinu3CV6NUhlooYWAmZXgw4Vwz4mmJElY+Fpe4rdRGxKd5AFt9qnxUxyJajILlmi6jZTnAgaeCVk0sX1Wh+qc2+UeMKvN+yzBSPpdZowZ5Bu3Y93d4fgy9Qyic5V/qvYKjzdqyO1vVxd0l4kI2GYjG/rFHBb6DLRDHMPIzN8nnGNQougz4n23Mvlr3vHoNMG3ZqCbbZ8WKw5eo80aJu/FAHOs8F+Io/k7uCOkUUTUhgoTfua648PUZJFV711SCVkRsoNfe4zoqoy8nBofDtiEiXCwahboj1OMQSiZ69Bp2Adn8hULTBGM0aKMnejHIMevxqbWNb9nOltgsCiJ66C7guW+67ak9tzEgX3Y4xD0hu4hHQ0jTQyxLpJ7ePL4ZriXyoxKqspmUL9TduDdkhXIRfofaqkmqfIUuiyrDc2LlWXP8CYFb3fq1Pw=
services:
- docker
after_success:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=pwegrzyndocking/footballassistant
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
deploy:
  provider: heroku
  app: football-assistant
  api_key:
    secure: RvL1LHIR9XukgzLdX3tFqvbtsLEtYwmewAiKw2ZxxUh/UAVzE2E3xZj6W7t6EGr/1h7Ss2sS7+sVZWbh5MYNwRVDdrQxnmRImDc6HiwjcwQAtHiAaqKN/GM+9ZsRABnsqSowm3CavDEoBA4HN8vejIAe+WnO6OrmfbBYq8hkWhwqLSDRH4jUc9PfLbvSYhO4fE5Ng3ZopvEL4gB+eyRJY036bQcpoyc2lni22bekGTYpZVHybghm64VdAIHAHjqGVp5EskP+Inz+9h9r8j0tqVjOYc3JvkRm9eO8Un4immKwF27jGy7DqPs8LqnZKb1CfYX85i4CLBqAIIO/kdTqa9F33Dlfl7EX5pQHaZSrC7FVsK1ld5ZY3UckHavifLDeSxgHGCC7QVgBQWMnlWnJLtNsNSTD98x/YzdxNMy1XIJodUefCRVBaPsHDVJLj+8D4pndWFFt1IVmlsWRk6IMtWRZJ3eJu9AbBqYsfVkIEKnUaI0UQ0witYKAbEd2eZwk4k+3OjaiC/2mcfDLLmtxeeUFBYbaAX5Tf+iN4rKT2l3NID1xDWNWAcKg6KXbVMf+i2YVZIUMez6+9t6KxUwCAw/Xt8popsBUDl/IJlDX/Jwj1fIj0A81rvl7GuBZVb4uWinBZ/mr94vhcrir5jqdFSQkS27lOEMhYm183Dkj+ys=
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
