sudo: required
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x mvnw
script:
- "./mvnw clean install -B"
- sonar-scanner
env:
  global:
  - secure: SdWMcO8909pbZavfabnNUGU18qdl7uHdFjnjv1XgbzQ+xYKGrHgnN+aC70f5TFywtmvlfijz3ykmIegSuqwUqa2KRCKYZF8xv/okJOPn54fNhrr6lEqgfIGjeWkj3uwll7JpHvg3klaGJ57GuvtHb5W8VDJsXADl0NIo/Rhf7pDYEgn21D8+i0gE/2pcV4s50kZWLx+vSO0dGlNMRW3zL6xrIfW+cMlKtocKV4Xz5nLZ2kS1OAyEpaPu2hGwWxGnC9xwQhFoFxhnddy5lUSdZ9SgQYW2xI2RCxeIE6om+LZ5Vwnu4y/W0vWgNHXFP14BOvsHuKe9RpoJ1BrKmzp+D24Ups7sEno9YL5L2XDZAWfWjjmInxtRjzWagXZqEJ4eRbHxMrx4U92azTIrXF+uDQMYdDKsME6m7x4vbyJlPWP9MeDROJqjUxvEZkUHTMSn1UjJDbbUGVP5EdXMK9Cd1dt+HlXP6No+F5gu341L+GfUlb8+jzVhlhqeXnccOfa6H4Yl9fI+2AKHwet7+RNO3Zr7w3uGdsY6/A2eu5srmBsjorFZnQPWgGPxIg6gzjKQn1Iqy6ZzIA7/sjV3WUOKpcOnIhpYAF8/8zd5cmpM5wFm3tWmlbNYx/fn/oqPITcO9lMPP0JcUKfbbMWLbcWH/SfipWdB6HmOi/kt9jrgMRc=
  - secure: nBdWORyt12M8rcfEvS3Yu/06josuKDoAFXqdPXtOaRPCb8Mf3UNAaXUpFpn5f885rdstS/jQ2ybGyx+9nZlz+BBpcSzFV/7j+SDadMm83v5Q7Y+3lklgHBzb9B4N7glEsBndqWJT7Lk1UYIUyFICp96wreHpia77yEwhAOdsnZtrQVL0+d7UH+qja1XIL6MPbFfki2TwDzR/ZXPRmACmV9iJCu/iIMJ65x2lfAfP/AgXSUyJSn8AWOVdpMaj6pZh/Sg9XXNqOXQIq21C97gkmHDHzNjh0WgWvokHVMKz0DjlMGMEkLZZc3HRD2cYi3hKRQUZj4KTToCJR1JcSOEm1Kv9SAzSVp5DwjkP2MglFeVCx26ZQBHlLjaMWnid10Jx5s4NMPiD7ROF9v3javeNqDtmB6i9VLFE3Ezr2LobOSpel+dW3+C9tpNX7tTEBm4mX8zx5qpQ7xUTbf+ohk4PZYcNGuP8Qv88gUKV1BeZnWnN5b9JbcrFpA2kpIr06bXC7uYckRM/MJ6jazi8N8RiybUdPhzBNwAg7y9I7XeVNsJ5HalngfAfYNfMZt7KQFHUQaptFEHa+oH2Gw/MDKjR/4Lnx+95NdLc892uv979HR5Y7h2tLpsK5852fxwpjQwzWmGLpnPb+Cp7rKrGqd+IdF2JxWv2whUoeXnhkeoGQ8w=
  - secure: V4a2DuffKoxUkYgnpm/Wu724e7FoKk0z6p/tV/LUSwLbExs4kbOnGHu9UD2WYbt8398ucYVUNHKDM5nH8tyRh5zS4BeVHRJ3oXqiNUSp4Pfkrei1n2fq61BMSQ39ciWrGpnqSndzQW92GEQ3XibiXNOzW1fxvmv4BZPMppbzBNEzWlpdKQdWVGsU15VpLrHnz2spALzGpr59QT/BNUFsIqSBvEj84CRxIp6E8szerVrfRKbNSmb5Lu8c2fmi4ukDPA8VcJ2vCXgYHlDbUIviCkQnJm0hKVih40ullepGk9wjUBOwPdv9MKGZFD4ZDJfRbCQilIOCeXjHBGVoYXDv0mh/OGGOdOXAQceWDCYbebtv6Uy5mWBLtt3mSd7erlIaww0gWHHRg59Z+aIMzF8tn/7NZz8RCPtoj5zjz15W7lToKSilmVZDcYAr2PH6E3Eqc7GYlOp1oe6cKcGW4rDZVmt2i/DycuMtQiuuVQFFHb4vxADXlLAkFHexEyLNexHKBsnVAngrWCFGDulLODNi3ewIF0lqUq/AmROcwsdk5ATcOesApS32mJG+4Fy3rQcpiH5MY9ZX1XbbKyAlc8+V6RgUb3wSIHj4pGhevPhgEBU3M30SUDeCn4jK6ADYkJ2Ut4ze2RdegbqraKTLFk5NW2513KcsjLGboBHHeizX0gE=
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: soDYTY+EbaefmAQoI2kCQANmp/rsNulDFRqN/GJRkzlJlMBrmkQ/HJ9D9TBla/RkqtaFqaLG6jH62itXUV4s9/1jPG5rl47/A+H0wf4rZiTl2c29mxps4FbfUr86P9xXGC6DArmhohWtCe1bsQcZ6HGLeHcylezigKea24zAOElMVb5T8fhdJcI/QCgXMEnS6U7ny5z43pYbU4Y0r7fYKze8q1ejxby/wNOx2cSqRcc57NObZHgA0HNGNF52iO5lQyEx9LyqHn+iCc1gnPpQLTCKf7kVJZPiTiaiMIYgQer5AZzdUL5Bi7pZrbWZOqfTA5h0hApVjnwq0rMQMkflHln2e9nwVujnCphcGkg/2qcP0aS4j/ldmuWiuzHOkLdqiSJWIX5TGjx56vKti4oVu6191aQSq1+K+gjvvnlGjTj7wdARrRleCVnAb81bJoAuYsad1oD/kextPsOI0fCR2A0RINOKDmqNDPVyc+1Jb0VB5OZuZfNaHRGoc+y08pH+EoRGk71pJA80GzA1AsiHxCeI8+yu6juXAW0awwFZVyQNeMdrZkWBWjXG6XrynCbk/2vBpFcBb9a9PgBSd8ICYfns22K2n/6hZqbX9GDVt0veL2v7nDyRCGwrCI3K8jzuiStcWF9R76gPFA5jySic9+cbEXwTjP4YwT9MSGd4XAM=
  - secure: Dn2frqexZGloBHa/FDn40cjA7N3z8htebmNiJd+PL9vDjzzQoPeQyhiNx+HIjDNpV/EPtuDdH+jME03r1toanX8AQpXTeEV7FDDiTrfnHSPCW9lw1t4aN3+EduYTlgmGyhGiVKqsMVYaQMC9J4uXOtzFV03ay8cARmQa2eIw5HNdhZW5CK7lzSSMNpNLDmssPRK6Bn6cdO5v4Pi5RYiLy4oOgx2dgIxThUcZDOYKICXnEIwX8hPbtcfcVoh8i6R56wKjY1UzLXe46C7LNHCkmU2Ear8yrp5vjEsWPchD4OXL9nQ05rKfz4iigBdLRv5NGVgD2uCG6VAK5//zJBYJbFuWt85BSV7w0VB7t4krGPBA3yQgjDLKdDNr0IFnEnVI+uhOxoEphHHCXgcTGayKP+m4rCVZF9jnjOY9ByFIM4TvO9b48EdKnEGn3Dle4UOKBn88ea51TcponI8SJxmk+mWAgNCODphRbzQ1AfW0qWllf65pV1Bnkp3hjARHeuSVP/DxpedeobyK590XRJdejMrZRIqOmSO9ja7g2E6ha4/h1y+ZiBqIE46SJHqnR74UaSPYxA8T7L/vGqAkmAUgbeGtkwH9k5X2Nrg0NgGvpYIKGUVHZrY8klus8p6qsHPIMxGB2Py1ToD4xZT6XIcckHaYip8kLpjnjrnMhIjiF2A=
addons:
  sonarcloud:
    organization: footballassitantteam
    token:
      secure: "$SONAR_TOKEN"
services:
- docker
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=pwegrzyndocking/footballassitant
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
deploy:
  provider: heroku
  api_key:
    secure: pBhO5miI3IxbDMpZwnZ+ZAk0+POaotferoA/PYko9+T1MBJo92pBFlvtZo7aElVMsthh0Zu1KiRq5GdZzAq8ciH7Oc6bmXM7cYxJdA7/0w7qHoz/EylkdcjyNGni1rHtOd6K9VQf45BR1oBQg/c9eoEGmiTrxI56N2+W0Cn9NlvzEkInD9+XUk1Tyegzv6oDFWHRMpwx/t8yiIXqI37Y6uYDvdwXbW6/LaAcK/GY2qR3OLtMuhWyc8yITmc8t4LuX6t8TiQDil67AxM6qaQSH9cjsWLJ6qDdpzEv7CqxhFeXWoZOaLKKdgHxoX6f8jQoDWnvZTQ2tvYCc+oan1kdeB9oiomGZKaZ5iz8PnMak+jofqPcRFboWH83QaK1xlcE4BVuVlmGfgO65u2J4s1b4THUEnzNImGxjLHIoLqL+zVWi6DGwjGVat4xmDSiB+Wzgjl24I7l/BjjuocNm2CIr/oeLs+gGTxtckwycm1qxaRDcry7e3mlwvcR8EfByupDH/QA7bbktfQGoQBCBr33tmAbWgro9smp2FgMQqbfWvcnmCRFu4XRS/gK2n3Tcu+kt2F99gqjX1h1+MTt19gLij5ROO6+mgqo6qA3N+Xqkej8b//Bk/aVhLAljcIrlV+ZMuSbRTv5PkZ5aEUicpN/W0/qSNin39gCdmv2s36ivCw=
    app: football-assistant
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
