sudo: required
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x mvnw
script:
- "./mvnw clean install -B"
- "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=53ae19da2f95e2cde8660b067f190855addc6dae"
env:
  global:
  - secure: Ho8p7wPDQ+X9dWHkBDUR8GuqZEF+62EbweDlSHAIuo/nmfEnJqrgWlp3Ek0ijXmW0V56B5FZVLK3eop/9dQMtRsnNVRR6EYqMloCDzbMzC4q2QrDCGWZV+2sMGR/NZEA96ooxLlAJiJeCCCg0BlLGxwj9iD9zvP9FkUCud3rnKLHOlbUe9Kxk9KaeSoO3lm1eJETUOXYj0zGQ2OcZvIGeyW4qXS6MTL/LFCiKCJNw6Jgk+I4ORpzQ6YqdONWlz7FbF+lDRx+13+MG4rd1tP1qi6MlDQAD/PQQFIvmqhgK+F0Nxigdhxi2KNYgDgOh9O1jaIlItTl/77TLlQ9+xSE1Bw9yZWo13yXgvM4K+g70rRpim1+RIdpXUaVyFFYFxUuHKOa65VakbNTrcpT1IxhUWqXpPh0Q+aZgepIYKzK/6H43g4+NRC7+0qiZ45c2fgVyFnE/qUwQ/HzvNlfyA03wERsAR0LZDiHVoTmml/e7nFF6SGI0k9uAOBlUcJwNkysOvkZxr4jOixj/4EkuiIdENsh2KOT7fHeikh9Gkj1TbHfhlnBVdEq9hF3BfkzRwQCXs9fUVwvbcEnNWZnruMsX7c5KRKyfX0jmNmjxhWCnMeL+sYRV9tILmM4EI7EqEhVocgHH6UD8AKUEZKhEw4Cd1Dl3p7hD3gCBDLJ7lwQObo=
  - secure: BptDeLZo2I0uoCmPDFt22g1kqycj8RjiuocrLYrbe4wm6k+bGoEm/Jr6Ed/oq+jb5Zy3ylS11sqYYSghx3PGxXr3Y1f2qkQcun3spoZm2A8oXfBVrp2tbaEsBnsGCEq8AKvWHQoQ5r5JgJ3bSzBCUeRlUTmWJsiXaBOHuWpMm192B9QblwBoul4lgjmzAdyqelcMzYcLzsTaPQA+YYqQk43+uercDz9lJbv36f1fjWmVdOUGhpe7xoRvB6wGQX+11MKc0EnNj/hJ8VLyfsGE14aj9HRqz+Fey6oi5WhvCv35NtouisQ1Gzm/DwtqsK7Rx2lJaj30O36LTUoAsuCuGu/wfyIdA8JduUh+3SNzJsgKGu8bhNpn2CESQ3ARYkGifLvVrxO9GQfvsuKpq/hU2/sH0v3XppFeEHGLOCPCkXI8MZSbNmrfkbgSRuD7yp104bmwhQuUAUDX3ZRcEO3pX1OfogQJqsB0/4RsUh0GScOsAwqREPl7RB+Z+tA18hQA1bd4zmXS30oyP0pDavWV+do4A919ZYUvm6p41B5//4rY8KSubPwhlsJwgNNaY7pQZiwFbvw+Tl6dDRUUyK1I5f6W1QzZT4eFdmWwSQWLg0DfsmP3C1ULIleigHB54bKogonZqmj9PTk46v1iFuNsA7ikiFEHJ6deNM9ot/M3JMc=
  - secure: atSQrBcDDJa7SMIeZBjUkF09s9OixWgtKFvX4qx4yB2gN5JO+GBbLUxtiGnrqQYFWA69qQE7saXITwlZB7XkMGMG8WIG8bgEBllB6+DtIcR6NKGMeki03MPMLcoz9ViAUbrbpU2eyBRgqEkS5qWia4Wg3BNwDy0Jc4X5CLrOjLGH4/ZyMQZqa9NWe7/6QzlYhcj+/WnNxj/5qrJi9BzdcAxyyuV+1V8n+5z9wSZunS18b4JDvGRBEBbrzY8ogAfUWy7Uj///8P9TcOE24Plu//Fhd3L5RAlNy5IIbzX4sRHUg5gzhcdostMdwv4Sewu8/0YYoI0mtqI1F1ejEo33wJrssegK1p0ldkR/vEIDqZLn/yb8aWS4XPWVhOypJgQEDNDE+JFwOt+k6wd41laJ64ZhXtTxaA1ipbCp98Pg/EibGLeAfkPYOKbGrP5kTKjVN01DS0KHWqkcUUx5dtExRI4qn1YLGBVo3LMLZkGENYUx8zAg4P8Jq1R/SU7T0okmT7K2KtD8Ps148pP7RrjteG6b3QYOX720wOEFncd1JhDfhLrVRmV4GxjYMv9mlOAqTcwT2UZwXXMYtBRuczVAJZdgBOW+ScUx1VZQPcpWflZeEoDabnJ8QNmvS7vRtEPkGlnabOyCDuJlwGCo9tNvGZfpjSziu6F4Fi5uxJJs7LY=
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: jTO1zjJbXCSIl1xrW9UadmsX4jHTvUDg1BAzalfKyv/nJRycJO7tN9MaRDY6zPf/tg46e2rKq1APgHRGkg671cf1QPa8oLSXjCc+WSd+2AfM/QDzf5/BWWDkO59nT6nSJTbSRlQqh95gGide/adznWkoI0o69a+nkftaVyNAN4FCdrtqXG85j/eKg2NUKVHEsmh/ORXJJMWBhFFoOYkw+l7nWFvw7NH8ehZCic2GXeiqW+h7m1SFmpKlohqsogHIfYCgq1HwmmhdFOgLzztAjm4leOahFKquW3tcgvBJ5qFYWwILw1ilYJYVvzKzp/VGqxY2Hrh6jvZY0IqHy+RajQCBcCybdkSvzbA4rtJ7+Ac2olLk8J3i0aY9bPMOmQBLycFCLO2LAtRc1bODgTWvVc8R/C1gk5ppi5H185YtxNEwnY+JFoes3h3Dc8jViGcNqsbxAHhT41Dbiu57zz+xIQXi2PvA7I27s9mjG2Az+wr7BtCvdVGFs2X0fIMFM+WHmFyvHVkHfYaixoaitQVY7nefQu3AnDcAHUt9uyy92lllciUIODip0Xwx8m7nsKW+fI1anZIlY/+kA17bJvq2Trjmw331SVQnV/r+PoDf94I/2hGpYIWIOM3KYKfZDu1x4mxtJbD+9p5cQIExbLfHk0l1nvPDQRAbBfah/s2v/dk=
addons:
  sonarcloud:
    organization: footballassitantteam
    token:
      secure: "$SONAR_TOKEN"
services:
- docker
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=pwegrzyndocking/footballassitant
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
deploy:
  provider: heroku
  api_key:
    secure: pBhO5miI3IxbDMpZwnZ+ZAk0+POaotferoA/PYko9+T1MBJo92pBFlvtZo7aElVMsthh0Zu1KiRq5GdZzAq8ciH7Oc6bmXM7cYxJdA7/0w7qHoz/EylkdcjyNGni1rHtOd6K9VQf45BR1oBQg/c9eoEGmiTrxI56N2+W0Cn9NlvzEkInD9+XUk1Tyegzv6oDFWHRMpwx/t8yiIXqI37Y6uYDvdwXbW6/LaAcK/GY2qR3OLtMuhWyc8yITmc8t4LuX6t8TiQDil67AxM6qaQSH9cjsWLJ6qDdpzEv7CqxhFeXWoZOaLKKdgHxoX6f8jQoDWnvZTQ2tvYCc+oan1kdeB9oiomGZKaZ5iz8PnMak+jofqPcRFboWH83QaK1xlcE4BVuVlmGfgO65u2J4s1b4THUEnzNImGxjLHIoLqL+zVWi6DGwjGVat4xmDSiB+Wzgjl24I7l/BjjuocNm2CIr/oeLs+gGTxtckwycm1qxaRDcry7e3mlwvcR8EfByupDH/QA7bbktfQGoQBCBr33tmAbWgro9smp2FgMQqbfWvcnmCRFu4XRS/gK2n3Tcu+kt2F99gqjX1h1+MTt19gLij5ROO6+mgqo6qA3N+Xqkej8b//Bk/aVhLAljcIrlV+ZMuSbRTv5PkZ5aEUicpN/W0/qSNin39gCdmv2s36ivCw=
    app: assistant
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
